# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 15:55
from __future__ import unicode_literals

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('images', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField((('archive_list', wagtail.core.blocks.StructBlock((('archives', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock()), ('time', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.URLBlock()), ('label', wagtail.core.blocks.CharBlock())))), ('documents', wagtail.core.blocks.ListBlock(wagtail.documents.blocks.DocumentChooserBlock())))))),))),))),
                ('description', models.CharField(max_length=200)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
            ],
            options={
                'verbose_name': 'Archive',
            },
            bases=('wagtailcore.page',),
        ),
    ]
