# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 15:55
from __future__ import unicode_literals

import apps.contrib.mixins
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Calendar',
            },
            bases=(apps.contrib.mixins.PaginatorMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('place', models.CharField(max_length=32)),
                ('contact', models.EmailField(max_length=254)),
                ('short_description', models.CharField(help_text='Shown on the homepage.', max_length=112)),
                ('description', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Event',
            },
            bases=('wagtailcore.page',),
        ),
    ]
