# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpage',
            name='short_description',
            field=models.CharField(blank=True, max_length=112),
        ),
    ]
