language: python
dist: bionic
python:
- '3.6'
cache:
  pip: true
  npm: true
install:
- nvm install 8
- npm install
- npm run build
- pip install -r requirements/dev.txt
script:
- python manage.py makemigrations --dry-run --check --noinput
- isort --diff -rc -c apps tempelhof
- flake8 apps tempelhof --exclude migrations,settings
- npm run lint
deploy:
- provider: script
  script: scripts/deploy.sh
  on:
    branch: master
env:
  global:
    secure: k53Oy/lLsW9FebkI861XTnUEsIu7dSVTH54berS8iwnHsswXU/yKJUGCSDSqqYbAJQpQ8aY8cPuxzg6PdfGem5iH57AifYWvkdpY7Pr4QBg0voFZ1ZG2sz8IIP7DWmtMWwihqICzvjHdiW2mG1vZuM6tTpxIETBLp95qQj2M5/N7BKH+XiXNMAssqpnnOe86N/XoooHXyRFL/pkU4Atr6FyGVuYZrb92AH/S0re+Sx2/GCTSVrglL7i9XRmPJmtmpZGrjKajRsbZc57U+HrFBotuRVtem/pZl1SH5s4L6zf83+NDjJ/69ezhXwCW0dDvjqJz/zoLEGg6un32+JtpvBtpDgMOL9v9reZbCXy0i+C8aKzIreO3nbKy+nlq7fJfZnaJ4EQoBC7mBnNeGgfOXSnOmvj/lYjHZW+Z0lk5OJetj19dfuI/pqtaNSIX4zvOMZUz9jaUwt1yInuFueJiOI6kybbR85/kpeziq/KjAt8HXeInPPDWxjW0NrCNxkOv2u9J+xrFfX4N4pK19OJq2dxL9cyLcWRYXtcJ2iYIk4DG/PhW3oLJxPc6vKFL1nYPMWML3wnHJSCGED+0daY8fQsmFfkTvGK/99qJ1iCyltdaLF2uzu7qv5NvME3HkWDHKuXiV/ZYfn6Xy7gOvHX4aXTcstqvN+4s1UwOEaWqw+c=
