# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 15:55
from __future__ import unicode_literals

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField((('documents_list', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('body', wagtail.core.blocks.RichTextBlock(required=False))))),))),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Documents',
            },
            bases=('wagtailcore.page',),
        ),
    ]
