# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 10:03
from __future__ import unicode_literals

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspage',
            name='body',
            field=wagtail.core.fields.StreamField((('documents_list', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('body', wagtail.core.blocks.RichTextBlock(required=False))))), ('Text', wagtail.core.blocks.RichTextBlock()))),
        ),
    ]
