# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('docs', '0002_allow_richtextblock_in_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='docspage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
