# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 13:25
from __future__ import unicode_literals

import apps.home.blocks
import apps.projects.blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_allow_raw_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='body_block',
            field=wagtail.wagtailcore.fields.StreamField((('text', wagtail.wagtailcore.blocks.RichTextBlock(icon='doc-full', template='home/blocks/text.html')), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock(template='home/blocks/text.html')), ('teasers', wagtail.wagtailcore.blocks.StructBlock((('teasers', wagtail.wagtailcore.blocks.ListBlock(apps.home.blocks.TeaserBlock)),))), ('columns', wagtail.wagtailcore.blocks.StructBlock((('columns', wagtail.wagtailcore.blocks.ListBlock(apps.home.blocks.ColumnBlock)),))), ('projects', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('projects', wagtail.wagtailcore.blocks.ListBlock(apps.projects.blocks.CurrentProjectBlock))))), ('updates', wagtail.wagtailcore.blocks.StructBlock((('status', wagtail.wagtailcore.blocks.PageChooserBlock(target_model=['blog.BlogEntryPage'])), ('calendar', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=False)),))))))), blank=True),
        ),
    ]
