# Generated by Django 2.2.2 on 2019-06-21 09:03

import apps.home.blocks
import apps.projects.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_simplepage_body_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(icon='doc-full', template='home/blocks/text.html')), ('html', wagtail.core.blocks.RawHTMLBlock(template='home/blocks/text.html')), ('teasers', wagtail.core.blocks.StructBlock([('teasers', wagtail.core.blocks.ListBlock(apps.home.blocks.TeaserBlock))])), ('columns', wagtail.core.blocks.StructBlock([('columns', wagtail.core.blocks.ListBlock(apps.home.blocks.ColumnBlock))])), ('projects', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('projects', wagtail.core.blocks.ListBlock(apps.projects.blocks.CurrentProjectBlock, help_text='Chose one or more Project Pages. Other pagetypes will result in an error.', target_model='projects.ProjectPage'))])), ('updates', wagtail.core.blocks.StructBlock([('status', wagtail.core.blocks.PageChooserBlock(page_type=['blog.BlogEntryPage'])), ('calendar', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False))]))]))]),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='body_block',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(icon='doc-full', template='home/blocks/text.html')), ('html', wagtail.core.blocks.RawHTMLBlock(template='home/blocks/text.html')), ('teasers', wagtail.core.blocks.StructBlock([('teasers', wagtail.core.blocks.ListBlock(apps.home.blocks.TeaserBlock))])), ('columns', wagtail.core.blocks.StructBlock([('columns', wagtail.core.blocks.ListBlock(apps.home.blocks.ColumnBlock))])), ('projects', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('projects', wagtail.core.blocks.ListBlock(apps.projects.blocks.CurrentProjectBlock, help_text='Chose one or more Project Pages. Other pagetypes will result in an error.', target_model='projects.ProjectPage'))])), ('updates', wagtail.core.blocks.StructBlock([('status', wagtail.core.blocks.PageChooserBlock(page_type=['blog.BlogEntryPage'])), ('calendar', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False))]))]))], blank=True),
        ),
    ]
